<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>todo</string>
		<string>todone</string>
	</array>
	<key>name</key>
	<string>ToDone</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#everything</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>complete</key>
		<dict>
			<key>begin</key>
			<string>^(\s*)(\+!?)(\-+)?</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.completed.todone</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.completed.secondary.todone</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!\1)|^\s*$|^(?=\1[^\s])</string>
			<key>name</key>
			<string>storage.type.task.completed.todone</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>^\s+(\+)?(!?\-+)</string>
					<key>name</key>
					<string>keyword.operator.completed.secondary.todone</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#ignore</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#task-over-raw-note</string>
				</dict>
			</array>
		</dict>
		<key>everything</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#complete</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#ignore</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#task-class</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lvl-disaster</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lvl-1</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lvl-2</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lvl-3</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lvl-4</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#lvl-5</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#note</string>
				</dict>
			</array>
		</dict>
		<key>ignore</key>
		<dict>
			<key>begin</key>
			<string>(?x)
^
  (\s*)
  (\.)(\+?!?\-+[12345]?)
  \s*
  (?:\(
    ([^\)]+)
  \))?
</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.ignore.todone</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.ignore.secondary.todone</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.ignore.desc.todone</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!\1)|^\s*$|^(?=\1[^\s])</string>
			<key>name</key>
			<string>storage.type.task.ignore.todone</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.ignore.secondary.todone</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s+\.?\+?\s*!?\s*\-+</string>
					<key>name</key>
					<string>keyword.operator.task.todone</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#task-over-raw-note</string>
				</dict>
			</array>
		</dict>
		<key>lvl-1</key>
		<dict>
			<key>begin</key>
			<string>(\s*)(\-{1}|\-(1))\s+((?:://|/(?!//)|[^:\n/])*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>symbol.definition.task-heading.todone</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.task.lvl1.todone</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.task.numeral.lvl1.todone</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.task.lvl1.todone</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!\1)|^(?=\s*\n)|^(?=\1[^\s])</string>
			<key>name</key>
			<string>storage.type.task.todone</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#everything</string>
				</dict>
			</array>
		</dict>
		<key>lvl-2</key>
		<dict>
			<key>begin</key>
			<string>(\s*)(\-{2}|\-(2))\s+((?:://|/(?!//)|[^:\n/])*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>symbol.definition.task-heading.todone</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.task.lvl2.todone</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.task.numeral.lvl2.todone</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.task.lvl2.todone</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!\1)|^(?=\s*\n)|^(?=\1[^\s])</string>
			<key>name</key>
			<string>storage.type.task.todone</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#everything</string>
				</dict>
			</array>
		</dict>
		<key>lvl-3</key>
		<dict>
			<key>begin</key>
			<string>(\s*)(\-{3}|\-(3))\s+((?:://|/(?!//)|[^:\n/])*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>symbol.definition.task-heading.todone</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.task.lvl3.todone</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.task.numeral.lvl3.todone</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.task.lvl3.todone</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!\1)|^(?=\s*\n)|^(?=\1[^\s])</string>
			<key>name</key>
			<string>storage.type.task.todone</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#everything</string>
				</dict>
			</array>
		</dict>
		<key>lvl-4</key>
		<dict>
			<key>begin</key>
			<string>(\s*)(\-{4}|\-(4))\s+((?:://|/(?!//)|[^:\n/])*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>symbol.definition.task-heading.todone</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.task.lvl4.todone</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.task.numeral.lvl4.todone</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.task.lvl4.todone</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!\1)|^(?=\s*\n)|^(?=\1[^\s])</string>
			<key>name</key>
			<string>storage.type.task.todone</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#everything</string>
				</dict>
			</array>
		</dict>
		<key>lvl-5</key>
		<dict>
			<key>begin</key>
			<string>(\s*)(\-{5}|\-(5))\s+((?:://|/(?!//)|[^:\n/])*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>symbol.definition.task-heading.todone</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.task.lvl5.todone</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.task.numeral.lvl5.todone</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.task.lvl5.todone</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!\1)|^(?=\s*\n)|^(?=\1[^\s])</string>
			<key>name</key>
			<string>storage.type.task.todone</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#everything</string>
				</dict>
			</array>
		</dict>
		<key>lvl-disaster</key>
		<dict>
			<key>begin</key>
			<string>(?x)
(\s*)
(!)
  (?:
    (\-{1}|\-(1))\s+((?:://|/(?!//)|[^:\n/])*:?) |
    (\-{2}|\-(2))\s+((?:://|/(?!//)|[^:\n/])*:?) |
    (\-{3}|\-(3))\s+((?:://|/(?!//)|[^:\n/])*:?) |
    (\-{4}|\-(4))\s+((?:://|/(?!//)|[^:\n/])*:?) |
    (\-{5}|\-(5))\s+((?:://|/(?!//)|[^:\n/])*:?) 
    
  )
</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>symbol.definition.task-heading.todone</string>
				</dict>
				<key>10</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.task.numeral.lvl3.todone</string>
				</dict>
				<key>11</key>
				<dict>
					<key>name</key>
					<string>entity.name.task.lvl3.todone</string>
				</dict>
				<key>12</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.task.lvl4.todone</string>
				</dict>
				<key>13</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.task.numeral.lvl4.todone</string>
				</dict>
				<key>14</key>
				<dict>
					<key>name</key>
					<string>entity.name.task.lvl4.todone</string>
				</dict>
				<key>15</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.task.lvl5.todone</string>
				</dict>
				<key>16</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.task.numeral.lvl5.todone</string>
				</dict>
				<key>17</key>
				<dict>
					<key>name</key>
					<string>entity.name.task.lvl5.todone</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.disaster.begin.todone</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.task.lvl1.todone</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.task.numeral.lvl1.todone</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>entity.name.task.lvl1.todone</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.task.lvl2.todone</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.task.numeral.lvl2.todone</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>entity.name.task.lvl2.todone</string>
				</dict>
				<key>9</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.task.lvl3.todone</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!\1\s)|^(?=\s*\n)|^(?=\1[^\s])</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.class-block.todone</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.condition.disaster.todone</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#everything</string>
				</dict>
			</array>
		</dict>
		<key>note</key>
		<dict>
			<key>begin</key>
			<string>(?=.)</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>storage.task-note.todone</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>((?!///)[^`])+
</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#note-em</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#raw-note</string>
				</dict>
			</array>
		</dict>
		<key>note-em</key>
		<dict>
			<key>begin</key>
			<string>`</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.note.em.begin.todone</string>
				</dict>
			</dict>
			<key>end</key>
			<string>`</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.note.em.end.todone</string>
				</dict>
			</dict>
			<key>name</key>
			<string>storage.task-note.em.todone</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\`</string>
				</dict>
			</array>
		</dict>
		<key>raw-note</key>
		<dict>
			<key>begin</key>
			<string>///</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.note.raw.begin.todone</string>
				</dict>
			</dict>
			<key>end</key>
			<string>///</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.note.raw.end.todone</string>
				</dict>
			</dict>
			<key>name</key>
			<string>storage.task-note.raw.todone</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#note-em</string>
				</dict>
				<dict>
					<key>match</key>
					<string>((?!///)[^`])+
</string>
				</dict>
			</array>
		</dict>
		<key>task-class</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\/\*</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.class-block.todone</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\*\/</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.class-block.todone</string>
						</dict>
					</dict>
					<key>name</key>
					<string>entity.name.class.todone</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^[^\s\.\-+!].*$</string>
					<key>name</key>
					<string>entity.name.class.todone</string>
				</dict>
			</array>
		</dict>
		<key>task-over-raw-note</key>
		<dict>
			<key>begin</key>
			<string>///</string>
			<key>end</key>
			<string>///</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>`</string>
					<key>end</key>
					<string>`</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\`</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.todone</string>
	<key>uuid</key>
	<string>93118f22-fcc3-4007-9de2-74fcbb17f143</string>
</dict>
</plist>
